name: On push to master
on:
  push:
    branches:
      - master
      - test-pr
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-18.04
    steps:
      - name: Print github context JSON
        run: |
          echo "toJson(github)=${{ toJson(github) }}"
  push-a-commit:
    name: Push a commit
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "touch"
      - name: Push changes
          # Based on https://github.com/ad-m/github-push-action.
          remote_repo="https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push "${remote_repo}" HEAD:${{ github.ref }}
  create-release:
    name: Create release
    runs-on: ubuntu-18.04
    steps:
      - id: release-info
        name: Extract release name
        run: |
          tag="v1.2.3-test
          echo "::set-output name=tag::${tag}"
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.release-info.outputs.tag }}"
          release_name: "${{ steps.release-info.outputs.tag }}"
